// This is the file for the customer-side API that the nodejs server needs to reach.

// *** HEADERS ***
// TransactionID: number, generated by nodejs, unique
// UserID: string, customer-side user id
// Content-Type: "application/json"
// UserName: string, part of the basic auth (password needs to be somewhere)
// SourceSystem: "FIXT"

// transactionID: isn't this the same as the header?
// startRow: number, tells where the returned data is from
// endRow: number, tells where the returned data stops
// totalRow: number, how large was the search result (might be split over several returns)
// statusCode: number? http code? based on CADM response
// statusMessage: string that goes along with statusCode

// UserID: same as above


// *** INITIAL SEARCH API ***
// GET http://hostname:port/services/BGWFIXT/v1/search/initialSearch/{SearchCategory}/{SearchType}/{SearchString}?start={Start}&end={End}&segment={Segment}
// Example: http://localhost:9070/services/BGWFIXT/v1/search/initialSearch/UpAccountNumber/invoice/1717908853703?start=1&end=400&segment=RETAIL,WHOLESALE,GOVT
// Valid categories: UpAccountNumber
// Valid types: invoice, subAccount, bundleAccount
// Valid search string: 10 or 13 digits
// Valid segments: RETAIL, WHOLESALE, GOVT (just those 3)


// *** GetBundleNodeDetails API ***
// GET http://hostname:port/services/BGWFIXT/v1/hierarchy/bundleNode
// ?hierarchyPointId={HierarchyPointId}
// or ?accountNumber={AccountNumber}
// hierarchy point gets priority so if both passed, account number is ignored
