db.dropDatabase();
db.roles.insert({name:"admin", index:1, editableFields:["startDate", "endDate"]});
db.roles.insert({name:"readonly", index:2, unreadableFields:["addressDetails"]});
db.statuses.insert({name:"unsent", index:0});
db.statuses.insert({name:"pending", index:1});
db.statuses.insert({name:"complete", index:2});
db.statuses.insert({name:"failure", index:3});
db.users.insert({name:"administrator", userId:"123456", role:1});
db.users.insert({name:"visitor", userId:"999999", role:2});
db.layouts.insert({nodeType: "I", field:"nodeLabel", category:"test1", column:1, row:1, displayName: "Node Label"});
db.layouts.insert({nodeType: "I", field:"startDate", category:"test1", column:1, row:2, displayName: "Start Date"});
db.layouts.insert({nodeType: "I", field:"address.city", category:"test1", column:1, row:3, displayName: "City"});
db.layouts.insert({nodeType: "I", field:"nodeId", category:"test1", column:1, row:4, displayName: "Node ID"});
db.topfives.insert({nodeType: "I", displayTags:["start date", "something", "something else", "another thing", "the last thing"]});
db.topfives.insert({nodeType: "BA", displayTags:["start date", "something", "something else", "another thing", "the last thing"]});
db.topfives.insert({nodeType: "CDG", displayTags:["start date", "something", "something else", "another thing", "the last thing"]});
db.topfives.insert({nodeType: "SA", displayTags:["start date", "something", "something else", "another thing", "the last thing"]});
