db.dropDatabase();
db.roles.insert({name:"admin", index:1, editableFields:["startDate", "endDate"]});
db.roles.insert({name:"readonly", index:2, unreadableFields:["addressDetails"]});
db.statuses.insert({name:"unsent", index:0});
db.statuses.insert({name:"pending", index:1});
db.statuses.insert({name:"complete", index:2});
db.statuses.insert({name:"failure", index:3});
db.users.insert({name:"administrator", userId:"123456", role:1});
db.users.insert({name:"visitor", userId:"999999", role:2});
db.layouts.insert({nodeType: "invoiceNode", field:"nodeLabel", category:"test1", column:1, row:1, displayName: "Node Label"});
db.layouts.insert({nodeType: "invoiceNode", field:"startDate", category:"test1", column:1, row:2, displayName: "Start Date"});
db.layouts.insert({nodeType: "invoiceNode", field:"address.city", category:"test1", column:1, row:3, displayName: "City"});
db.layouts.insert({nodeType: "invoiceNode", field:"nodeID", category:"test1", column:1, row:4, displayName: "Node ID"});
db.layouts.insert({nodeType: "invoiceNode", field:"hierarchyPointID", category:"test1", column:1, row:5, displayName: "Hierarchy Point ID"});
db.layouts.insert({nodeType: "invoiceNode", field:"nodeType", category:"test1", column:2, row:1, displayName: "Node Type"});
db.topfives.insert({nodeType: "invoiceNode", displayTags:["nodeID", "nodeLabel", "hierarchyPointID", "startDate", "nodeType"]});
db.topfives.insert({nodeType: "bundleNode", displayTags:["nodeID", "nodeLabel", "hierarchyPointID", "startDate", "nodeType"]});
db.topfives.insert({nodeType: "cdgNode", displayTags:["nodeID", "nodeLabel", "hierarchyPointID", "startDate", "nodeType"]});
db.topfives.insert({nodeType: "subaccountNode", displayTags:["nodeID", "nodeLabel", "hierarchyPointID", "startDate", "nodeType"]});
